In [1]:
import numpy as np

In [2]:
# Array Manipulatipn

In [3]:
arr = np.random.randint(1,10, (3,4))

In [4]:
arr

array([[8, 4, 3, 8],
       [9, 2, 3, 9],
       [6, 3, 7, 4]])

In [5]:
arr.reshape(2,-767)

array([[8, 4, 3, 8, 9, 2],
       [3, 9, 6, 3, 7, 4]])

In [6]:
arr.T

array([[8, 9, 6],
       [4, 2, 3],
       [3, 3, 7],
       [8, 9, 4]])

In [7]:
arr.flatten()

array([8, 4, 3, 8, 9, 2, 3, 9, 6, 3, 7, 4])

In [8]:
arr1 = np.array([1,2,3,3,4])

In [9]:
arr1.ndim

1

In [10]:
np.expand_dims(arr1, axis=1)

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [11]:
np.expand_dims(arr1, axis=0)

array([[1, 2, 3, 3, 4]])

In [12]:
data = np.array([[1], [2], [3]])

In [13]:
data

array([[1],
       [2],
       [3]])

In [14]:
np.squeeze(data)

array([1, 2, 3])

In [15]:
arr1

array([1, 2, 3, 3, 4])

In [16]:
np.repeat(arr1,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [17]:
arr1

array([1, 2, 3, 3, 4])

In [18]:
np.roll(arr1, 2)

array([3, 4, 1, 2, 3])

In [19]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [20]:
# Binary Operations

In [21]:
arr1 = np.random.randint(1,10, (3,4))

In [22]:
arr2 = np.random.randint(1,10, (3,4))

In [23]:
arr1

array([[4, 4, 1, 1],
       [5, 7, 8, 2],
       [4, 6, 9, 8]])

In [24]:
arr2

array([[8, 9, 3, 7],
       [4, 9, 8, 6],
       [2, 8, 8, 7]])

In [25]:
arr1+arr2

array([[12, 13,  4,  8],
       [ 9, 16, 16,  8],
       [ 6, 14, 17, 15]])

In [26]:
# *, -, /

In [27]:
arr1%arr2

array([[4, 4, 1, 1],
       [1, 7, 0, 2],
       [0, 6, 1, 1]])

In [29]:
arr1 ** arr2

array([[   65536,   262144,        1,        1],
       [     625, 40353607, 16777216,       64],
       [      16,  1679616, 43046721,  2097152]])

In [30]:
arr1 & arr2

array([[0, 0, 1, 1],
       [4, 1, 8, 2],
       [0, 0, 8, 0]])

In [31]:
~arr1

array([[ -5,  -5,  -2,  -2],
       [ -6,  -8,  -9,  -3],
       [ -5,  -7, -10,  -9]])

In [32]:
arr1 | arr2

array([[12, 13,  3,  7],
       [ 5, 15,  8,  6],
       [ 6, 14,  9, 15]])

In [33]:
arr1 > arr2

array([[False, False, False, False],
       [ True, False, False, False],
       [ True, False,  True,  True]])

In [34]:
# string function

In [35]:
arr = np.array(['vee', 'kumar'])

In [36]:
arr

array(['vee', 'kumar'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['VEE', 'KUMAR'], dtype='<U5')

In [38]:
np.char.title(arr)

array(['Vee', 'Kumar'], dtype='<U5')

In [39]:
np.char.capitalize(arr)

array(['Vee', 'Kumar'], dtype='<U5')

In [40]:
# Mathimatical funcions

In [41]:
arr1

array([[4, 4, 1, 1],
       [5, 7, 8, 2],
       [4, 6, 9, 8]])

In [42]:
np.sin(arr1)

array([[-0.7568025 , -0.7568025 ,  0.84147098,  0.84147098],
       [-0.95892427,  0.6569866 ,  0.98935825,  0.90929743],
       [-0.7568025 , -0.2794155 ,  0.41211849,  0.98935825]])

In [43]:
np.cos(arr1)

array([[-0.65364362, -0.65364362,  0.54030231,  0.54030231],
       [ 0.28366219,  0.75390225, -0.14550003, -0.41614684],
       [-0.65364362,  0.96017029, -0.91113026, -0.14550003]])

In [44]:
np.tan(arr1)

array([[ 1.15782128,  1.15782128,  1.55740772,  1.55740772],
       [-3.38051501,  0.87144798, -6.79971146, -2.18503986],
       [ 1.15782128, -0.29100619, -0.45231566, -6.79971146]])

In [45]:
np.log10(arr1)

array([[0.60205999, 0.60205999, 0.        , 0.        ],
       [0.69897   , 0.84509804, 0.90308999, 0.30103   ],
       [0.60205999, 0.77815125, 0.95424251, 0.90308999]])

In [46]:
np.exp(arr1)

array([[5.45981500e+01, 5.45981500e+01, 2.71828183e+00, 2.71828183e+00],
       [1.48413159e+02, 1.09663316e+03, 2.98095799e+03, 7.38905610e+00],
       [5.45981500e+01, 4.03428793e+02, 8.10308393e+03, 2.98095799e+03]])

In [47]:
np.sqrt(arr1)

array([[2.        , 2.        , 1.        , 1.        ],
       [2.23606798, 2.64575131, 2.82842712, 1.41421356],
       [2.        , 2.44948974, 3.        , 2.82842712]])

In [48]:
np.power(arr1,2)

array([[16, 16,  1,  1],
       [25, 49, 64,  4],
       [16, 36, 81, 64]])

In [49]:
np.mean(arr1)

4.916666666666667

In [50]:
np.var(arr1)

6.909722222222222

In [51]:
np.max(arr1)

9