In [7]:
import numpy as np

In [8]:
l = [2,3,4,5]

In [9]:
ar = np.array(l)

In [10]:
ar

array([2, 3, 4, 5])

In [11]:
type(ar)

numpy.ndarray

In [12]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [15]:
np.asarray(l)

array([2, 3, 4, 5])

In [16]:
np.asanyarray(l)

array([2, 3, 4, 5])

In [14]:
b = np.matrix(l)

In [17]:
np.asanyarray(b)

matrix([[2, 3, 4, 5]])

In [18]:
a = np.array(l)

In [19]:
c = a

In [20]:
a

array([2, 3, 4, 5])

In [21]:
c

array([2, 3, 4, 5])

In [22]:
c[0] = 100

In [23]:
c

array([100,   3,   4,   5])

In [24]:
a

array([100,   3,   4,   5])

In [26]:
d = np.copy(a)

In [27]:
d

array([100,   3,   4,   5])

In [28]:
a

array([100,   3,   4,   5])

In [29]:
a[2] = 400

In [30]:
a

array([100,   3, 400,   5])

In [31]:
d

array([100,   3,   4,   5])

In [32]:
np.fromfunction(lambda i,j: i == j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [33]:
np.fromfunction(lambda i,j: i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [34]:
iterable = (i*i for i in range(5))

In [36]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
np.fromstring("234 'fff'", sep=' ')

/tmp/ipykernel_131/430166947.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("234 'fff'", sep=' ')


array([234.])

In [40]:
np.fromstring("sdsd ff", sep=' ')

/tmp/ipykernel_131/3277968494.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("sdsd ff", sep=' ')


array([], dtype=float64)

In [41]:
np.fromstring("234 555", sep=' ')

array([234., 555.])

In [42]:
# data type

In [43]:
i = [2,3,4,5,6,7]

In [52]:
ar = np.array(i)

In [53]:
ar.ndim

1

In [54]:
ar2 = np.array([[2,3,4], [3,4,5]])

In [55]:
ar2.ndim

2

In [56]:
ar.size

6

In [57]:
ar2.size

6

In [58]:
ar.shape

(6,)

In [59]:
ar2.shape

(2, 3)

In [60]:
ar.dtype

dtype('int64')

In [61]:
ar2.dtype

dtype('int64')

In [62]:
ar22 = np.array([(1.4, 33,43), (3,5,22.4)])

In [63]:
ar22

array([[ 1.4, 33. , 43. ],
       [ 3. ,  5. , 22.4]])

In [65]:
ar22.dtype

dtype('float64')

In [66]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [67]:
np.arange(2.3,5.6, .3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [68]:
list(np.arange(2.3,5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [70]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [71]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [74]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [76]:
np.ones(4)

array([1., 1., 1., 1.])

In [77]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [79]:
on = np.ones((2,3,2))

In [80]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [81]:
on * 5

array([[[5., 5.],
        [5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.],
        [5., 5.]]])

In [82]:
np.empty((3,5))

array([[4.66271146e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [83]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [85]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [87]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [88]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [89]:
np.logspace(2,5,10, base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [92]:
arr = np.random.rand(3,4)

In [93]:
import pandas as pd

In [94]:
pd.DataFrame(arr)

0         1         2         3
0  0.109653  0.863639  0.786765  0.641853
1  0.117939  0.121651  0.498672  0.335714
2  0.176409  0.283861  0.040716  0.011142

In [95]:
arr1 = np.random.randn(3,4)

In [96]:
pd.DataFrame(arr1)

0         1         2         3
0 -0.813205  0.513034  0.138282 -0.105105
1  0.478956 -0.568970 -0.859617  0.194085
2 -0.882175  1.289938  0.578443  1.687787

In [97]:
# randn generate data having mean 8 and standard deviation 1
# Rand generate data randomly

In [100]:
ranint = np.random.randint(1,110, (30,40))

In [102]:
pd.DataFrame(ranint).to_csv('test.csv')

In [103]:
arr = np.random.rand(3,4)

In [104]:
arr

array([[0.85138465, 0.43038618, 0.74912824, 0.48534069],
       [0.26321038, 0.84146795, 0.0093745 , 0.45644137],
       [0.77819502, 0.84983887, 0.31532382, 0.94438865]])

In [106]:
arr1 = arr.reshape(6,2)

In [110]:
arr1

array([[0.85138465, 0.43038618],
       [0.74912824, 0.48534069],
       [0.26321038, 0.84146795],
       [0.0093745 , 0.45644137],
       [0.77819502, 0.84983887],
       [0.31532382, 0.94438865]])

In [107]:
arr1[1][1]

0.4853406945200146

In [111]:
arr1[2:5,1]

array([0.84146795, 0.45644137, 0.84983887])

In [112]:
arr = np.random.randint(1,100, (5,5))

In [113]:
arr

array([[85, 66, 83, 12, 97],
       [91, 28, 84, 96, 39],
       [43, 75, 98, 80,  9],
       [31, 37, 51, 29, 23],
       [ 5, 88, 66, 81, 59]])

In [114]:
arr>50

array([[ True,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [False,  True,  True,  True, False],
       [False, False,  True, False, False],
       [False,  True,  True,  True,  True]])

In [115]:
arr[arr>50]

array([85, 66, 83, 97, 91, 84, 96, 75, 98, 80, 51, 88, 66, 81, 59])

In [116]:
arr

array([[85, 66, 83, 12, 97],
       [91, 28, 84, 96, 39],
       [43, 75, 98, 80,  9],
       [31, 37, 51, 29, 23],
       [ 5, 88, 66, 81, 59]])

In [121]:
arr[2:4, [1,2]]

array([[75, 98],
       [37, 51]])

In [124]:
arr[2:4, (1,2)]

array([[75, 98],
       [37, 51]])

In [125]:
arr[0][0] = 5000

In [126]:
arr

array([[5000,   66,   83,   12,   97],
       [  91,   28,   84,   96,   39],
       [  43,   75,   98,   80,    9],
       [  31,   37,   51,   29,   23],
       [   5,   88,   66,   81,   59]])

In [127]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [128]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [129]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [130]:
arr1+arr2

array([[2, 3, 2],
       [2, 3, 2],
       [3, 2, 3]])

In [131]:
arr1-arr2

array([[ 0,  1,  0],
       [ 0, -1,  0],
       [-1,  0,  1]])

In [132]:
arr1/arr2

array([[1. , 2. , 1. ],
       [1. , 0.5, 1. ],
       [0.5, 1. , 2. ]])

In [133]:
arr1*arr2

array([[1, 2, 1],
       [1, 2, 1],
       [2, 1, 2]])

In [134]:
"""
Matrix multiplication: 
mat1 = m * n
mat2 = p * q
if n = p, then only matrix multiplication works and produces m * q  => row * column
"""

'\nMatrix multiplication: \nmat1 = m * n\nmat2 = p * q\nif n = p, then only matrix multiplication works and produces m * q  => row * column\n'

In [135]:
arr1@arr2

array([[5, 6, 4],
       [4, 4, 3],
       [6, 5, 4]])

In [136]:
arr1

array([[1, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [137]:
arr2

array([[1, 1, 1],
       [1, 2, 1],
       [2, 1, 1]])

In [138]:
"""
matrix multiplication
1*1+2*1+1*2 1*1+2*2+1*1 1*1+2*1+1*1

5 6 4
"""

'\nmatrix multiplication\n1*1+2*1+1*2 1*1+2*2+1*1 1*1+2*1+1*1\n\n5 6 4\n'

In [139]:
arr1/0

/tmp/ipykernel_131/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [140]:
# numpy - Broadcasting

In [141]:
arr = np.zeros((4,4))

In [142]:
row = np.array([1,2,3,4])

In [146]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [147]:
row

array([1, 2, 3, 4])

In [148]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [149]:
col = np.array([[1,2,3,4]])

In [150]:
col

array([[1, 2, 3, 4]])

In [151]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [152]:
col.shape

(1, 4)

In [153]:
col.T.shape

(4, 1)

In [154]:
arr + col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [155]:
arr1 = np.random.randint(1,4, (3,4))

In [156]:
arr1

array([[1, 1, 3, 1],
       [3, 2, 1, 3],
       [3, 3, 1, 1]])

In [157]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.73205081, 1.        ],
       [1.73205081, 1.41421356, 1.        , 1.73205081],
       [1.73205081, 1.73205081, 1.        , 1.        ]])

In [158]:
np.exp(arr1)

array([[ 2.71828183,  2.71828183, 20.08553692,  2.71828183],
       [20.08553692,  7.3890561 ,  2.71828183, 20.08553692],
       [20.08553692, 20.08553692,  2.71828183,  2.71828183]])

In [159]:
np.log10(arr1)

array([[0.        , 0.        , 0.47712125, 0.        ],
       [0.47712125, 0.30103   , 0.        , 0.47712125],
       [0.47712125, 0.47712125, 0.        , 0.        ]])