In [1]:
import numpy as np
list_ = ['1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)


In [2]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [3]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.
"""

'\nQ1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code\nto print the data types of both the variables.\n'

In [6]:
array_list.dtype

dtype('<U1')

In [8]:
type(list_)

list

In [9]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
"""

'\nQ2. Write a code to print the data type of each and every element of both the variables list_ and\narra_list.\n'

In [17]:
myList = list(map(lambda n : type(n), list_))
print(myList)

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [18]:
myList2 = list(map(lambda n : type(n), array_list))
print(myList2)

[<class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>, <class 'numpy.str_'>]


In [24]:
"""
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
"""

"""
list_ element data type is: string
array_list element data type is: Integer
"""

'\nlist_ element data type is: string\narray_list element data type is: Integer\n'

In [25]:
array_list = np.array(object = list_, dtype = int)

In [26]:
array_list

array([1, 2, 3, 4, 5])

In [27]:
myList = list(map(lambda n : type(n), list_))
print(myList)

[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [28]:
myList2 = list(map(lambda n : type(n), array_list))
print(myList2)

[<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]


In [29]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)


In [30]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size
"""

'\nQ4. Write a code to find the following characteristics of variable, num_array:\n(i) shape\n(ii) size\n'

In [32]:
num_array.shape

(2, 3)

In [33]:
num_array.size

6

In [34]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
"""

'\nQ5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array\ncreation function.\n'

In [36]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?
"""

'\nQ6. Create an identity matrix of shape (5,5) using numpy functions?\n'

In [39]:
arr = np.array([1,1,1,1,1])

In [40]:
np.diag(arr)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])