In [10]:
import numpy as np

In [11]:
# sorting, searching and counting function

In [12]:
arr = np.array([2,3,4,5,643,12,523,4545,43,6,43])

In [13]:
arr

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [14]:
np.sort(arr)

array([   2,    3,    4,    5,    6,   12,   43,   43,  523,  643, 4545])

In [15]:
np.searchsorted(arr, 34)

6

In [16]:
arr2 = np.array([0,0,23,454,0,3,0,0])

In [18]:
np.count_nonzero(arr2)

3

In [19]:
arr

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [20]:
np.where(arr > 6)

(array([ 4,  5,  6,  7,  8, 10]),)

In [22]:
np.extract(arr>6, arr)

array([ 643,   12,  523, 4545,   43,   43])

In [23]:
# Byte swapping

In [24]:
arr

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [25]:
arr.byteswap()

array([  144115188075855872,   216172782113783808,   288230376151711744,
         360287970189639680, -9006636304787570688,   864691128455135232,
         793196484370628608, -4534843349785378816,  3098476543630901248,
         432345564227567616,  3098476543630901248])

In [26]:
# copy and views

In [27]:
a = np.copy(arr)

In [28]:
a

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [29]:
b = arr.view()

In [30]:
b

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [31]:
arr

array([   2,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [32]:
b[0] = 44

In [33]:
b

array([  44,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [34]:
arr

array([  44,    3,    4,    5,  643,   12,  523, 4545,   43,    6,   43])

In [35]:
# Matrix library

In [36]:
import numpy.matlib as nm

In [37]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [39]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
nm. eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [42]:
# liner algebra

In [43]:
arr1 = np.array([[2,3], [4,5]])

In [44]:
arr2 = np.array([[5,3], [2,5]])

In [45]:
np.dot(arr1, arr2)

array([[16, 21],
       [30, 37]])

In [46]:
arr1

array([[2, 3],
       [4, 5]])

In [47]:
arr2

array([[5, 3],
       [2, 5]])

In [48]:
arr1@arr2

array([[16, 21],
       [30, 37]])